### ISSUE TITLE
Docker and docker-compose Config

### ISSUE THREAD

**Issue by benyaminl** [rkusnadiii/dotnettask#12]
For dockerfile 
there are seems some problem on the restore process that hasn't done yet, but exited, so we can just change the Dockerfile to :

```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# create cert for Dev SSL @see https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md#linux
RUN dotnet dev-certs https -ep /source/examplemvc.pfx -p 12345
RUN dotnet user-secrets -p /source/examplemvc.csproj init
RUN dotnet user-secrets -p /source/examplemvc.csproj set "Kestrel:Certificates:Development:Password" "12345"

# Disable Cache on Docker when build 
# ALWAYS USE --build-arg CACHE_DATE=$(date +%Y-%m-%d:%H:%M:%S)
# If you need to drop cache before this, use --build --no-cache flag
# @see https://stackoverflow.com/a/38261124/4906348
ARG CACHE_DATE=not_a_date
# copy and publish app and libraries
COPY . .
RUN dotnet publish -o /app 

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app .
# Copy the Source file @see https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md#linux
COPY --from=build /source/examplemvc.pfx /root/.aspnet/https/examplemvc.pfx
COPY --from=build /root/.microsoft/usersecrets /root/.microsoft/usersecrets
# Supporting SQL Server 2008 R2 TLS 1.0 @see https://programmer.ink/think/net-5-error-accessing-mssql-in-docker.html
# @see https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver15#possible-reasons-and-solutions
RUN sed -i 's/TLSv1.2/TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "/app/examplemvc.dll"]
```

Beware that we need to use dotnet publish because well... we need `wwwroot` to be included (for static files), after that we can check whether it's added or not by run the container using /bin/bash or just build then run. IF the file isn't copied, just change the `.csproj` content to include `<Folder Include="wwwroot/" />`

eg : 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="6.0.23" />
    <Folder Include="wwwroot/" />
  </ItemGroup>
</Project>
```

Then for the docker-compose file 

```
version: '3.7'

services:
  webapi:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment: # see https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md#linux
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Development__Password: "12345"
      MSSQL_DB: "${MSSQL_DB}"
      MSSQL_USER: "${MSSQL_USER}"
      MSSQL_PASS: "${MSSQL_PASS}"
      MSSQL_PORT: "${MSSQL_PORT}"
      MSSQL_HOST: "${MSSQL_HOST}"
```

To use the env variable, change the GetConfig based on the ENV on the docker, refer to https://github.com/benyaminl/dotnet-core-playground/blob/master/Program.cs#L30-L39
